// <auto-generated />
using System;
using DeviceManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeviceManagementOnly.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260624072641_add models")]
    partial class addmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DeviceManagementOnly.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("ColumnName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FinalizedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RecordId")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("TableName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.DeviceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DeviceCategories");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.DeviceDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BarcodeNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid>("DeviceMasterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IMEI")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LongName")
                        .HasColumnType("longtext");

                    b.Property<string>("MACAddress")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ParentDeviceDetailId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("PurchaseCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RFIDTagNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("SIMNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext");

                    b.Property<string>("TagNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("WarrantyExpiry")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceMasterId");

                    b.HasIndex("IMEI")
                        .IsUnique()
                        .HasFilter("IMEI IS NOT NULL");

                    b.HasIndex("ParentDeviceDetailId");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("SerialNumber IS NOT NULL");

                    b.ToTable("DeviceDetails");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.DeviceMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("DataFormat")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DeviceCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DeviceLongName")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceShortName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DeviceTypeId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ModelSpecificationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCategoryId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("ModelSpecificationId");

                    b.ToTable("DeviceMasters");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.DeviceModelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ModelSpecificationId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("ModelSpecificationId");

                    b.ToTable("DeviceModelMappings");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.DeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid>("DeviceCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<string>("IconColor")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Protocol")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("SupportedFeature")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCategoryId");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.ModelCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ModelCategories");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.ModelParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Capacity")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid>("DeviceModelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EndOfLife")
                        .HasColumnType("longtext");

                    b.Property<string>("Feature")
                        .HasColumnType("longtext");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("longtext");

                    b.Property<string>("Intro")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ModelCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParameterValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Processor")
                        .HasColumnType("longtext");

                    b.Property<string>("Protocol")
                        .HasColumnType("longtext");

                    b.Property<string>("RAM")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("Storage")
                        .HasColumnType("longtext");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Uses")
                        .HasColumnType("longtext");

                    b.Property<string>("WarrantyDuration")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceModelId");

                    b.HasIndex("ModelCategoryId");

                    b.ToTable("ModelParameters");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.ModelSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DeviceTypeId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("ModelSpecifications");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.UnitMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("UnitMasters");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.DeviceDetail", b =>
                {
                    b.HasOne("DeviceManagementOnly.Models.DeviceMaster", null)
                        .WithMany()
                        .HasForeignKey("DeviceMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceManagementOnly.Models.DeviceDetail", "ParentDevice")
                        .WithMany("SubDevices")
                        .HasForeignKey("ParentDeviceDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentDevice");
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.DeviceMaster", b =>
                {
                    b.HasOne("DeviceManagementOnly.Models.DeviceCategory", null)
                        .WithMany()
                        .HasForeignKey("DeviceCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DeviceManagementOnly.Models.DeviceType", null)
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DeviceManagementOnly.Models.ModelSpecification", null)
                        .WithMany()
                        .HasForeignKey("ModelSpecificationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.DeviceModelMapping", b =>
                {
                    b.HasOne("DeviceManagementOnly.Models.DeviceType", null)
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceManagementOnly.Models.ModelSpecification", null)
                        .WithMany()
                        .HasForeignKey("ModelSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.DeviceType", b =>
                {
                    b.HasOne("DeviceManagementOnly.Models.DeviceCategory", null)
                        .WithMany()
                        .HasForeignKey("DeviceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.ModelParameter", b =>
                {
                    b.HasOne("DeviceManagementOnly.Models.ModelSpecification", null)
                        .WithMany()
                        .HasForeignKey("DeviceModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceManagementOnly.Models.ModelCategory", null)
                        .WithMany()
                        .HasForeignKey("ModelCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.ModelSpecification", b =>
                {
                    b.HasOne("DeviceManagementOnly.Models.DeviceType", null)
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DeviceManagementOnly.Models.DeviceDetail", b =>
                {
                    b.Navigation("SubDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
